name: Example Action with Email

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 22f3001833@ds.study.iitm.ac.in
        run: echo "Hello, world!"
